name: chronovault
description: ChronoVault – Sort the ages. Race the clock. Unlock history.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
          weight: 700
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
          weight: 700
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora-Italic.ttf
          style: italic
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
    - family: EBGaramond
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf
        - asset: assets/fonts/EBGaramond-Italic.ttf
          style: italic

  assets:
    - assets/sounds/
    - assets/fonts/
